add item'

diff --git a/.github/workflows/succeed-on-timeout.yaml b/.github/workflows/succeed-on-timeout.yaml
--- a/.github/workflows/succeed-on-timeout.yaml
+++ b/.github/workflows/succeed-on-timeout.yaml
@@ -12,6 +12,6 @@ jobs:
         timeout-minutes: 1 # Times out after 1 minute
         run: sleep 90 || echo '::set-output name=failure_reason::Script failed due to something random' # Set your output error if your script fails. Include useful message
       - name: check previuos step
-        run: "[ -n '${{ steps.longrunner.outputs.failure_reason }}' ] && echo '::error::${{ steps.longrunner.outputs.failure_reason }}' && exit 1"
+        run: "[ -n '${{ steps.longrunner.outputs.failure_reason }}' ] && echo '::error::${{ steps.longrunner.outputs.failure_reason }}' && exit 1 || echo ''"
       - name: continue to do more stuff
         run: echo "I did more stuff"
