add cleanup

diff --git a/.github/workflows/succeed-on-timeout.yaml b/.github/workflows/succeed-on-timeout.yaml
--- a/.github/workflows/succeed-on-timeout.yaml
+++ b/.github/workflows/succeed-on-timeout.yaml
@@ -10,7 +10,8 @@ jobs:
         id: longrunner
         continue-on-error: true
         timeout-minutes: 1 # Times out after 1 minute
-        run: sleep 90 || echo '::set-output name=failure_reason::Script failed due to something random' # Set your output error if your script fails. Include useful message
+        # We add the echo \r so that we remov ethe previuos ::error:: written by the timeout
+        run: sleep 90 && echo -en "\r" || echo '::set-output name=failure_reason::Script failed due to something random' # Set your output error if your script fails. Include useful message
       - name: check previuos step
         run: "[ -n '${{ steps.longrunner.outputs.failure_reason }}' ] && echo '::error::${{ steps.longrunner.outputs.failure_reason }}' && exit 1 || echo ''"
       - name: continue to do more stuff
